### ISSUE TITLE
Main Menu Item Click not displaying data

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#1]
@biplovbhandari Main Menu items when clicked should go to show the data directly instead having to click on the sub menu item again to view thedate. For example (/eden/org/index) - when I click on More ---> Organizations, it gives me a blank page. Then I have to click on the sub-menu Organization (/eden/org/organisation) to see the data. Why not directly display the data by removing an additional step.

**Comment by biplovbhandari** [comment]
@waidyanatha That is the starting page (eden/org/index), which is editable by CMS. However if you want I can move it to directly navigate to /eden/org/organisation

**Comment by biplovbhandari** [comment]
http://eden.sahanafoundation.org/wiki/BluePrint/CAPBroker/GUIDesign#MainMenu
