### ISSUE TITLE
Alert Approval list

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#10]
A user with Alert Approver privileges should be presented with a menu option  to access all approved and pending alerts (/eden/cap/alert/review). The list should display who created it and who approved it; in addition to the details already there.

**Comment by biplovbhandari** [comment]
approver have all the required menus

**Comment by waidyanatha** [comment]
Where is the URL to the user guide wiki about this ?

**Comment by waidyanatha** [comment]
make sure that this is discussed in the User Roles / Responsibilities in the blueprint and user guide, then give both URLs

**Comment by biplovbhandari** [comment]
http://eden.sahanafoundation.org/wiki/UserGuidelines/SAMBRO#SystemMenu

**Comment by waidyanatha** [comment]
Let's move the wiki content to Publisher; even if you have to duplicate it
