### ISSUE TITLE
Relay Update, Cancel, All Clear options unavailable

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#11]
I created a user nuwan@sahana.... first gave it the default Authenticated user role. Next upgraded to Alert Editor and Approve. Then I opened an alert already issued with the intent of either Relay or Update. None of the buttons were available?

**Comment by biplovbhandari** [comment]
@waidyanatha does not happen for me...might check again in your side

**Comment by waidyanatha** [comment]
First created a user: nuwan@example.com (pwd = changeme). Then created an alert using admin@example.com with event type = earthquake and template = "tsunami ..... ". When into manage users and added nuwan@....  with role Alert Editer. Logged out of admin@example.com and logged in ans nuwan@.... cannot even see the partially edited alert. 

Login as nuwan@... and see yourself. There's are two earthquake alerts created by Bayu.

Just because you try some step and it works for you does not mean it is solved. Need to analyze more carefully, considering every possibility.

**Comment by biplovbhandari** [comment]
1. 

I logged in as admin@example.com. I see two earthquake alerts created by anggabayu@ait.asia, having alert id of 60 and 57.
![image](https://cloud.githubusercontent.com/assets/4207677/15102125/d0c7df9c-15c5-11e6-94d3-08ccb071d6a1.png)

Logged out and logged in as nuwan@example.com. I can see those two earthquake alerts in table list.
![image](https://cloud.githubusercontent.com/assets/4207677/15102142/0e2679f2-15c6-11e6-9118-17098de374bb.png)

I can open each of them and all the options are available.
![image](https://cloud.githubusercontent.com/assets/4207677/15102151/2e372c0a-15c6-11e6-81f1-3c949aa16467.png)

![image](https://cloud.githubusercontent.com/assets/4207677/15102164/41fe21d0-15c6-11e6-9233-9b546d178fcf.png)

2.

First created a user: biplov@ait.asia
![image](https://cloud.githubusercontent.com/assets/4207677/15102195/92e0c3f0-15c6-11e6-819d-ecdd6f445065.png)

Then created an alert using admin@example.com
![image](https://cloud.githubusercontent.com/assets/4207677/15102237/22c55ea4-15c7-11e6-98dc-fe74b7640df5.png)

Went into manage users and added biplov@ait.asia with role Alert Editor.
![image](https://cloud.githubusercontent.com/assets/4207677/15102242/3ccd44f6-15c7-11e6-8a98-4b12346b383e.png)

Logged out of admin@example.com and logged in as biplov@ait.asia. Can see the previously created alert.
![image](https://cloud.githubusercontent.com/assets/4207677/15102262/7b84aa54-15c7-11e6-8010-237bad60e9f3.png)

**Comment by waidyanatha** [comment]
You have not understood the problem yet. Has nothing to do with the two earthquake alerts created by Bayu. It is about the new alert created using admin@example.com. If unclear we can discuss.

**Comment by waidyanatha** [comment]
https://github.com/sahana/SAMBRO/issues/1
