### ISSUE TITLE
Validating and applying knowedge to attributes

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#12]
Important to apply the proper knowledge and logic in validating and suggesting values. Here's a list to start with. Think about all the attributes with coded values and let's create a list with all required logic in here:
- [x] **Message Status** (Draft) - need to check if message status has been changed from draft to alert or something else; see the transition diagram for the knowledge: http://eden.sahanafoundation.org/wiki/BluePrint/CAPBroker/GUIDesign#msgType.
- [ ] **Template/Event_Type** - once an Alert has been created for the first time, there is no need to show the template and Event_Type controls. User will not use them anymore; can be hidden. If the user used the wrong event type, then they should "Cancel" that alert and start a new one.
- [x] **Message Type** - after the first issuing of the message with setting the msgType=Alert, the same message can never be reissued as an Alert. It can be an Update, Cancel, Error, or All Clear. If during an update, error, cancel, or all-clear the user should never be allowed to set it to "Alert" again.
- [x] **Onset** - if onset is not set then it should default to effective date. 
- [x] **Parameter** - if the parameter name is not null and the value is null then user should be prompted to add the value
- [x] **Sender / SenderName** - If either Sender or SenderName is NULL then it should default to the email address and user Name, respectively.
- [x] **All attributes** - if the value is NULL then it can be hidden from being displayed in the Profile (FULL ALERT) page.
- [x] **Sent** - the sent date and time should be set to the current time when the message is saved for Alert, Update, Error, Cancel, and All Clear.
- [x] **CAP Mandatory values** - All CAP specification set mandatory (or REQUIRED) values should never be NULL. For example, If user forgets to set the Scope, they need to be prompted. For CAP REQUIRED values see the attributes highlighted in bold: http://docs.oasis-open.org/emergency/cap/v1.2/CAP-v1.2-os.html
- [x] **Recipients** - the recipients drop down shows even when the scope is not set. It should only appear and allow user to set a value, if and only if, scope is Public or Private

**Comment by waidyanatha** [comment]
ensure that this logic is discussed in the Blueprint/GUIdesign add URL here

**Comment by biplovbhandari** [comment]
http://eden.sahanafoundation.org/wiki/BluePrint/CAPBroker/GUIDesign#Validatingandapplyingknowledgetoattributes
