### ISSUE TITLE
Person Create vs Create Subscription

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#17]
There are two options in the Admin Controlled Manage Recipients
A) Alerting ----> Person ---- Create (/eden/pr/person/create) and 
B) Alerting ----> Person ---- Create Subscription (/eden/default/index/subscriptions?option=manage_recipient). 

We do not need the first option A). You can remove it from the Menu and replace with Option B) in the menu
The workflow should be:
- Admin creates a user (/eden/admin/user)
- Admin navigates to Manage Recipients (/eden/pr/subscription?option=manage_recipient)
- Admin click on Create Subscription (which now can be a menu item and not a button)
- Admin adds recipient to the list
- opens the group and adds recipient to member list

Create Subscription is not a good name for that button, replace with Add Recipient to List or something like that which is meaningful and reflects the function.

**Comment by waidyanatha** [comment]
all that's missing is the User Guide URL and the Blueprint URL describing the difference.

**Comment by waidyanatha** [comment]
We need a proper user instructions here: http://eden.sahanafoundation.org/wiki/UserGuidelines/Admin/UserManagement

Need to tell the story about

- Admin managed subscribers (forced push)
- Self subscribed users
- Register for an account

**Comment by biplovbhandari** [comment]
http://eden.sahanafoundation.org/wiki/UserGuidelines/SAMBRO#UserManagement

**Comment by waidyanatha** [comment]
The user guide, in general, should discuss the purpose of the function such as explaining what Admin managed Subscribers mean. Then tell the user what they do. This might be too much for you and that's why we needed a Technical Writer :-) 

The page you have parked the content is in the overview page and should be moved here: http://eden.sahanafoundation.org/wiki/UserGuidelines/SAMBRO/Implement#UserManagement

Thereafter, relevant listed items in the Subscribe, Publish, Implement, Administer should point to the appropriate sub sub sections.

**Comment by biplovbhandari** [comment]
updated
