### ISSUE TITLE
Parameters in Info block

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#19]
Parameters are not saving in message templates.
The labels are not key and value ... laymen need to understand .... is should be name and value

**Comment by waidyanatha** [comment]
why is the Myanmar Flood template showing a sahana:tsunami-wave-height-meters parameter?
Why is it showing a Falling Condition parameter, when we said that only parameters with prefix sahana: should be the only ones used?

**Comment by anggabayu21** [comment]
I'm not done with that, i just changed the value..

**Comment by waidyanatha** [comment]
https://github.com/sahana/SAMBRO/issues/37
