### ISSUE TITLE
Adding Branches to an Org is not Apparent

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#2]
@biplovbhandari Adding Branches - it is absolutely unclear how to add a branch? No menu items no instructions. Following the user guideline it says right click Add but it's confusing because the title says "create organization"; shouldn't it say "create branches"? There must be some instruction in the form reminding the user that they need to right click and ADD.

**Comment by waidyanatha** [comment]
Provide the User guideline URL here:

**Comment by biplovbhandari** [comment]
http://eden.sahanafoundation.org/wiki/UserGuidelinesOrganisationRegistry

**Comment by waidyanatha** [comment]
Thanks for the URL let me review before we close

**Comment by waidyanatha** [comment]
http://eden.sahanafoundation.org/wiki/UserGuidelinesOrganisationRegistry

the URL above is generic to Eden and does not discuss about the CAP OID for example, and adding Organization Branches with augmented CAP OIDs.

**Comment by biplovbhandari** [comment]
Linked from http://eden.sahanafoundation.org/wiki/UserGuidelines/SAMBRO#ImplementersSuperUsers (5) to http://eden.sahanafoundation.org/wiki/UserGuidelines/SAMBRO/Implement#ManagingtheRegisterofAlertingAuthoritiesandOIDs
