### ISSUE TITLE
Listing Lx (Provinces, Districts) for  given Polygon

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#27]
Philippines users were keen to list all the Provinces and Districts that are withing a Polygon. They would draw the polygon and either after saving or AJAX should add the list of Districts, Provinces (perhaps the largest Lx) that cover the polygon in the AreaDesc.

Another option might be to list the intersecting Lx values in as a parameter instead of the AreaDesc. 

This requirement came from Philippines.

**Comment by waidyanatha** [comment]
I tested on AIT demo - It only provides the Country level LX. Ideally, when we select the country level LX it should provide the Provincial/State Level, District Level, and Town/City level Lx if they are available. In the SAMBRO demo we should have the LX breakdown for, at least, Myanmar, Maldives, and the Philippines. If we have data for the others, then they should go in prepop. 

Once completed add the Blueprint URL and User Guide URL to this issue to close it.

**Comment by biplovbhandari** [comment]
The GIS Data cannot go in prepop. It takes considerable time to import those data and no one wants to wait for the installation to complete that long when its already long. Besides there could be memory problem which I have faced time and again. The guidelines and the methods are already explained here: http://eden.sahanafoundation.org/wiki/GIS/Data

**Comment by flavour** [comment]
We typically use a 'post-pop' script on servers to install the locations...server is operational before they import, but it still happens automatically on cleans of Dev instances.
What we don't want is blocking on local Dev installs - especially since SQLite is a blocking DB

**Comment by biplovbhandari** [comment]
Linked from http://eden.sahanafoundation.org/wiki/UserGuidelines/SAMBRO#ImplementersSuperUsers (12) to http://eden.sahanafoundation.org/wiki/GIS/Data

**Comment by waidyanatha** [comment]
I haven't seen the working version; does it automatically draw the polygon for a particular district when that one is selected?
