### ISSUE TITLE
Authenticated user Navigation

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#3]
@biplovbhandari How does the Authenticated user view the list of alerts from the Home Page? There is no menu item to click for the subscriber to review the list of all alerts. The home page may display only active alerts (i.e. expire date > today). But the subscriber may want to refer to an expired alert from the past.

At the time of login the Authenticated user is presented with the Alert list. I think the Home page would be a more appropriate docking point after sign in.

**Comment by biplovbhandari** [comment]
/cap/alert list all the alerts and can be filtered as expired, unexpired, internal alerts, external alerts, etc.

**Comment by waidyanatha** [comment]
Where is the URL to the user guide wiki about this ?

**Comment by biplovbhandari** [comment]
http://eden.sahanafoundation.org/wiki/UserGuidelines/SAMBRO#SubscribersAlertRecipients

http://eden.sahanafoundation.org/wiki/UserGuidelines/SAMBRO/Subscribe#FilterAlerts

**Comment by waidyanatha** [comment]
need to check the content myself to ensure it is all explained well. Let's not close these until such time I get to reviewing the blueprint and user guidelines.
