### ISSUE TITLE
Archived Alerts

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#31]
There should be an option for Authorized Users to view archived alerts; i.e. those that no longer display on the home page (/eden/default/index) because the expire < today. 

Even if it is possible to view them under the Alerting menu (/eden/cap/alert) the user has no option to navigate to the profile (/eden/cap/public/36/profile), which is much easier to read opposed to the alert edit GUIs.

**Comment by waidyanatha** [comment]
I suppose in the filters (which should have the option of show/hide) when the user selected ALL does that include the Archived Alerts too? If not we should provide sum way to view the old alerts.

**Comment by biplovbhandari** [comment]
http://eden.sahanafoundation.org/wiki/UserGuidelines/SAMBRO#SystemMenu

**Comment by biplovbhandari** [comment]
Please create separate issue for removing the alerts more than 12 months before

**Comment by waidyanatha** [comment]
12 months might be too long; be good to run some analysis to test what might be the optimal strategy for displaying. https://github.com/sahana/SAMBRO/issues/66
