### ISSUE TITLE
profile and read choices for individual alerts

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#32]
The users should have an option to select between viewing the alerts as view only using the editor GUIs or the . Perhaps give the option to switch to any of the view from the alert list (/eden/cap/alert) itself, may be two buttons for each alert profile view (/eden/cap/alert/103/profile) and the editor view (/eden/cap/alert/103/read). 

From each of the Profile View and Editor view to switch to the other view methods.

**Comment by waidyanatha** [comment]
Is this explained in the User Guideline? If not, enter it and add the URL here

**Comment by biplovbhandari** [comment]
The switch between profile and read are the default buttons well explained in the data tables here: /eden/cap/alert. I don't think this requires further explaination
