### ISSUE TITLE
Alert Hub

### ISSUE THREAD

**Issue by biplovbhandari** [sahana/SAMBRO#33]
If RSS (for eg. https://alerts.internetalerts.org/subscriptions/wmo) feed points to a cap xml (for eg. http://capcp1.naad-adna.pelmorex.com/2016-06-08/2016_06_08T04_54_00_00_00I2.49.0.1.124.e949a3f7.2016.xml) is determined to be a CAP 1.2 file, i.e. contains the header `<alert xmlns="urn:oasis:names:tc:emergency:cap:1.2">`, and we flag that RSS feed to be imported into our database, then it should be rendered in our common operating picture. Users should be able to relay those messages.

**Comment by waidyanatha** [comment]
Alert hub generally is based on external feeds. These feeds should be rendered on a Map as well; if they provide the polygons. We should create a secondary "home" page that would renders all these alerts. Especially, since PAGASA is using SAMBRO for visualization they need to view all the CAP alerts on SAMBRO that were published using their tools.

**Comment by biplovbhandari** [comment]
![image](https://cloud.githubusercontent.com/assets/4207677/18739410/a47542f4-80cd-11e6-9017-37134b8712f2.png)
![image](https://cloud.githubusercontent.com/assets/4207677/18739419/b7d02382-80cd-11e6-9275-61b037163cea.png)

**Comment by waidyanatha** [comment]
make sure the Blueprint discusses the essentials of the Alert Hub and provide that URL here.
Also ensure the User Guideline has instructions for the users and provide that URL here as well.

**Comment by waidyanatha** [comment]
A few issues related to http://sambro.meteopilipinas.gov.ph/

- [ ] PAGASA Alert Hub is showing alerts from Myanmar; feed needs to be cleaned up; any prepop of /ede/template/sambro/ph/pagasa , with feeds should be cleaned up
- [ ] Displaying all the feeds from day 1 to now is overwhelming the Common Alerting Picture (CAP) map with icons showing dozens of alerts form the same area. We should apply a strategy that by default shows only most recent (perhaps expire > today or expire > today - 30days); Similar to the Internal Alert CAP provide filters to view all, expired, etc. 
- [ ] The click Datalist asks me for a login? If these are public alerts then we don't need a login, no? http://sambro.meteopilipinas.gov.ph/eden/cap/alert?%7E.external=True
- [ ] There are some performance issues with the alert icons showing on the map; it takes several refreshing attempts to get it to display. 
- [ ] Filter Scope in the public Alert Hub seems redundant when all the alerts are public and nothing else?
- [ ] Rename Common Operating Picture to Common Alerting Picture

![pagasa_pshb_cap](https://cloud.githubusercontent.com/assets/543943/20207345/963fc7b0-a821-11e6-9de2-5704bf0b3aa3.png)

**Comment by biplovbhandari** [comment]
http://eden.sahanafoundation.org/wiki/UserGuidelines/SAMBRO#AlertHub

**Comment by waidyanatha** [comment]
Let's not dump everything in the [overview page](http://eden.sahanafoundation.org/wiki/UserGuidelines/SAMBRO). Learn to organize the content. The idea of the overview page is for user to quickly access the relevant info. First they identify their role and then select the functionality under that role.

Alert hub, for example, would be for Subscribers; hence the content should go in there. Same with the system menu if it is relevant to Publishers then it should go in that page. Go through the links listed under the 4 roles to realize where content should be organized.

**Comment by biplovbhandari** [comment]
the system menu i have kept in the overview page because the menus are common to all, trying to DRYing here

**Comment by waidyanatha** [comment]
DRYing? 

In this structure, Alert Hub is a sub topic of System Menu? Doesn't make sense. 

What is your intention of presenting the System Menu? Is it to give an overview of it? try to figure out the purpose and then find the appropriate place to park it. 

The main issue I highlighted was the Alert Hub content and Menu was just another example. If it's too difficult to figure out where to compartmentalize them, then leave as for now; I need to find time or other resources to do this properly.
