### ISSUE TITLE
Social media icons 

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#34]
we need to provide the twitter and facebook links in the Public (unauthenticated) homepage. These can be by providing the twitter and facebook icons. The icons link to the implementation specific accounts. Example, twitter feed of DMH or PAGASA or MMS / NDMC. 

Do we want to provide a settings.facebook type parameter with other relevant token values in the 000_config.py , which would make it easy for Admins to change, if needed; rather than hardcoding?

**Comment by waidyanatha** [comment]
How to the implementers connect the SocMed icons with the URL? Indicate in the Admin section how to link URL with Icon.

**Comment by biplovbhandari** [comment]
Linked from http://eden.sahanafoundation.org/wiki/UserGuidelines/SAMBRO#ImplementersSuperUsers (11) to http://eden.sahanafoundation.org/wiki/UserGuidelines/SAMBRO/Implement#ChangingtheSocialMediaIconLinks

**Comment by waidyanatha** [comment]
Why MM, what if PH or MV? Can't we give the generic SAMBRO code location? Ideally it should be in the config if not already.
