### ISSUE TITLE
Multiple Info and Multiple Alert

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#37]
Need to allow users to add multiple info blocks as in the case of Myanmar with Cyclone alert carrying information about the Storm Surge. Moreover. the effective area of the cyclone which would move inland is different for the storm surge. The storm surge will only effect the coastal area with swell waves.

**Comment by waidyanatha** [comment]
Hold off on this, I need to reassess to model the various scenarios.

**Comment by biplovbhandari** [comment]
the discussion in workshop was that we should use one event per alert and use reference element to say its origin or update

**Comment by waidyanatha** [comment]
That is Eliot's version because he models everything around RSS feeds. The v.1.2 specifications does not imply that. The dilemma here is whether the Cyclone is the event and whether the Storm Surge is an incident resulting from the event. In the case of Myanmar they don't want to generate two alerts. The question is how do we indicate the cyclone impacting area, the storm surge, and the heavy rain fall impacting areas in separate area blocks. These are all tied to the same event. If we are to create separate alerts then we need to add another button called "resulting event" or "child event" that would basically generate a new alert referencing the parent event, in this case the cyclone.

**Comment by waidyanatha** [comment]
Discuss the method we agreed on in the Blueprint then provide the URL to that discussion. As you recommended, agree that treating each one as an event with separate CAP messages and linking them through a common incident and the reference might be the way to go. It will also help simply with the processing and rendering as well. We won't need to add additional logic to parse the XML to differentiate.

Here's Art's reply

In principle having multiple Info blocks allows us to represent a complex situation such as you describe in a single Alert.  (Our planning scenario had to do with a “phased” warning where the onset would be at different times in different Areas, but I think your example is actually more interesting.)

Still, I confess that in practice I’d be a bit concerned that not all implementations fully implemented that capability, and so I’d probably send multiple single-Info messages bound by a shared <incidents> value just to be on the safe side.  That’s in no way a rejection of the multiple-Info approach, but merely a concession to an imperfect world of implementations in which provisions for such a relatively uncommon structure might be less mature.  Semantically the two are equivalent.

I’ll confess that I hadn’t really considered putting a collection of Alerts inside a single Alert reference.  Again, my concern about such recursion would be about presenting implementations with a more sophisticated input than they’d been coded for / tested against.  It’s certainly permissible under the standard, though.

I’ve thought about the case of having multiple Infos share a single Area, but never came up with a simpler way to do it than just repeating the Area.  Around here the main use of multiple Infos is for multiple versions of the same message in different languages, so we need to duplicate the Areas as well in order that each areaDesc can be in the language of its Info.

**Comment by waidyanatha** [comment]
Based on our discussion, several months back, we decided to offer another button and process to invoke a new Alert from an existing one but carrying the identifier across into the reference element. 

### Preliminaries
- Implementers have created message templates for each event
### Create Alert
- User creates an issues an alert (e.g. for Cyclone)
- User opens recently sent Cyclone alert and clicks "Create Associated Alert" button (like we do with the update, cancel, relay, etc)
- User selects new event type and template to general an Alert (e.g. Swell Waves)
### Update, Cancel, All-Clear
- User updates the Cyclone Alert and issues it
- Then User selects the Swell Wave alert to update and issue it
- The Swell Wave update should check whether any associated alerts, like the Cyclone alerts has been updated; in the event it should include the cyclone update identifier in the reference element of the Swell Wave update as well.

**Comment by waidyanatha** [comment]
Moved to CAPBroker missing features: http://eden.sahanafoundation.org/wiki/BluePrint/CAPBroker#Missingfeatures:
