### ISSUE TITLE
PDF documents for authorized alerts

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#39]
Both Myanmar and Philippines require PDF documents with the event specific information.
Process should be:

1) User creates/saves alert and submits for approval;
2) On-Click for approval, the alert the PDF file is generated and uploaded (or linked to the alert message) as a Resource element
3) Approver selects the alert to click edit and then download the PDF file to print a copy
4) Once PDF file is signed that serves as an approval. 
[Exception] - if there are errors in the PDF alert message (file) the Approver or Editor has to make the corrections and re-submit, which will follow step 2), 3), & 4)
5) Signed and approved PDF is uploaded as a Resource element (replacing the unsigned doc), 
6) Approver clicks "approved" to disseminate the message
7) The file will appear in the CAP Profile page in the Resource segment with a link to the PDF
8) The file will be attached in the email to Subscribers 
     8.1) File is attached on all Administrator defined subscribers
     8.2) Self-Subscriber can configure to receive or not to receive the PDF in email

Note - each Organization will have their own format an requirement whether or not to publish a PDF. Will need to think of a way to include that in some kind of a configuration option or to be flagged in the Organization registry.

@biplovbhandari upload the sample PDF here.
@biplovbhandari write this in Myanmar and Philippines blueprints as a user story as well as the requirements.

**Comment by waidyanatha** [comment]
Rename English Form to Bulletin (EN)

**Comment by biplovbhandari** [comment]
attach the CAP XML in the email

**Comment by waidyanatha** [comment]
Give the Subscriber the option to set whether or not they want to receive the XML
