### ISSUE TITLE
showing garbage characters

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#4]
@biplovbhandari In Myanmar server - I created a subscription for Cyclone and then selected all the priorities; after saving I see some garbage like this: Event Type: Cyclone Warning
Priorities: ['\xe1\x80\x99\xe1\x80\xaf\xe1\x80\x94\xe1\x80\xb9\xe1\x80\x90\xe1\x80\xad\xe1\x80\xaf\xe1\x80\x84\xe1\x80\xb9\xe1\x80\xb8\xe1\x80\xa1\xe1\x80\xb1\xe1\x80\xbb\xe1\x80\x81\xe1\x80\xa1\xe1\x80\xb1\xe1\x80\x94 (\xe1\x80\xa1\xe1\x80\x94\xe1\x80\xae\xe1\x80\xb1\xe1\x80\x9b\xe1\x80\xac\xe1\x80\x84\xe1\x80\xb9\xe1\x80\xa1\xe1\x80\x86\xe1\x80\x84\xe1\x80\xb9\xe1\x80\xb7)', 'Storm Warning ( Brown color)', 'Storm News (Depression) (yellow color)', '\xe1\x80\x9b\xe1\x80\x81\xe1\x80\xad\xe1\x80\xaf\xe1\x80\x84\xe1\x80\xb9\xe1\x80\x80\xe1\x80\x99\xe1\x80\xb9\xe1\x80\xb8\xe1\x80\x9b\xe1\x80\xad\xe1\x80\xaf\xe1\x80\xb8\xe1\x80\x90\xe1\x80\x94\xe1\x80\xb9\xe1\x80\xb8']
Languages:['en-US']

**Comment by waidyanatha** [comment]
It might very well be a Unicode issue. We need to provide instructions to
the user in FAQ and other places instructing them that if they have not
installed the relevant Unicode then they need to do so. Also point to
instructions or provide instructions how to accomplish it.

**Comment by biplovbhandari** [comment]
[http://eden.sahanafoundation.org/wiki/Deployments/SAMBRO/FAQs#UnicodeDisplayProblem](Unicode Display Problem)

**Comment by waidyanatha** [comment]
Is there someway that Eden/SAMBRO can alert the user that they may need to install the Unicode or fix the issues? For example, when the user sets the language does that trigger Eden to check if the computing device supports that language?

Always think about the normal users; not you, Fran, or I. They will very likely be unaware of Unicode and some sort of a warning may trigger them to talk to their Admin or us.
