### ISSUE TITLE
KML Hazard Trajectory Map

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#45]
Find a way to integrate the PAGASA KML files for showing the cyclone trajectory or hazard vulnerability area.
 Example: http://publicalert.pagasa.dost.gov.ph/file/track.kmz

**Comment by biplovbhandari** [comment]
http://v2.meteopilipinas.gov.ph/#

**Comment by waidyanatha** [comment]
moved to CAPBroker missing features: http://eden.sahanafoundation.org/wiki/BluePrint/CAPBroker#Missingfeatures:

**Comment by waidyanatha** [comment]
moved to CAPBroker missing features:  http://eden.sahanafoundation.org/wiki/BluePrint/CAPBroker#Missingfeatures:
