### ISSUE TITLE
Server Ping

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#49]
Move the code from Lutz or create a new shell script to ping the 3 servers: PH, MM, MV and email them an alert when down. Maintain the logs to estimate the mean time to failure.

**Comment by waidyanatha** [comment]
I'm almost done with writing a shell script and activating it. Already tested on localhost and works fine.

Couple of issues:

- [ ] the ping command doesn't need to be working well and looking into changing it to using telnet port 80 instead. Doesn't work for Philippines mostly.
- [ ] Getting it to work on AWS EC2 free tier - the mail client is not the same as mine and some minor fixes are needed.

**Comment by frommberger** [comment]
Did you put the script on Github? If not, please do.

**Comment by waidyanatha** [comment]
@frommberger  Github doesn't allow to upload .sh and .csv files; so I've added a .txt extension to each file; just remove the .txt part and run pingsam.sh. 

[master.csv.txt](https://github.com/sahana/SAMBRO/files/693825/master.csv.txt)
[pingsam.sh.txt](https://github.com/sahana/SAMBRO/files/693826/pingsam.sh.txt)

**Comment by biplovbhandari** [comment]
git, of course, allows the upload of CSV and shell script (example https://github.com/sahana/eden/blob/master/modules/templates/SAMBRO/Demo/cap_warning_priority.csv and https://github.com/sahana/eden_deploy/blob/master/add_demo_site.sh) but not sure if need to create a separate project or not. But better to create project, any similar use-case can be redirected there and maybe someone interested can contribute back?

**Comment by waidyanatha** [comment]
Sure git code allows for uploading any type of file. It was this comment box that I was referring to; only allows like txt, png, etc :-)

I thought people generally wrote their own code for this kind of small things; I'd be happy to start a new project but it certainly should not be a Sahana project because it has no relevance to the Sahana code base; agree?
