### ISSUE TITLE
Edit Subscription after saving gives NO option

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#5]
@biplovbhandari ​Edit Subscription does is very different from create subscription; i.e. 2 different forms and different attributes. I should be able to edit my subscription with resetting the priority​ or event type or receiving options. Also when subscribing to an event, the validation should check to see if user has created a subscription with the same event type; if there are duplicate event types then user should be warned.

**Comment by waidyanatha** [comment]
>
>    - if you click on one record then yes it must show the selected value,
>    but if you click on create subscription it shows formatted form. Same logic
>    applies throughout the application
>
>
​At the time of creating the subscription to an event and priority the user
may have made a mistake and would like to change from all priorities to a
single priority. That is not possible because there is no option to edit
the saved record. Intuitively, the user should be able to make that change
rather than deleting it and recreating it.​

**Comment by waidyanatha** [comment]
Did you fix this? 

Now when I am in /eden/pr/subscription and click Open on a saved alert subscription e.g. /eden/default/index/subscriptions?subscription_id=68) it presents the original values with Event Type, Priority, Language, and Notification options, which is what I wanted.

**Comment by biplovbhandari** [comment]
This was already there. Maybe cache in your computer.
