### ISSUE TITLE
Register User activates Admin

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#51]
I clicked logout, while logged in as admin@example.com. Then I logged out (http://sambro.geoinfo.ait.ac.th/eden/default/user/logout). After that clicked on Request for Account (http://sambro.geoinfo.ait.ac.th/eden/default/user/profile). SAMBRO automatically logs me in as admin. That is a major security issue.

**Comment by flavour** [comment]
This would indeed be a major issue!
I cannot replicate it however...I tried both locally & using the AIT SAMBRO demo server...both work just as I would expect for me.
What client were you using?

**Comment by waidyanatha** [comment]
I was using the AIT Demo on Firefox. I did replicate it a few times but now, today, I can't seem to replicate it :-)
