### ISSUE TITLE
Filtered Alert Hub (Sahana)

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#52]
We will host a filtered alert hub on AWS and provide all these feeds: https://docs.google.com/a/sahanafoundation.org/spreadsheets/d/1nGR7CGwJV5eWgfRpQraFuBn4chZigBOzXjCfpmEb3ew/edit?usp=sharing_eixpa_nl&ts=57f34060

it would be a production version at alerthub.sahanafoundation.org (this would be different from the sambro.sahanafoundation.org, which will also be on AWS but is mostly for testing, demos, and training)

Before we provide more features on the filtering mechanisms we can add this list; see if you can directly pull through CSV.

Devin pulled it together. Perhaps we can provide a paid service to anyone who wants to generate or relay alerts. This may require some performance testing and code optimization as well. 

Eliot's presentation: http://preparecenter.org/sites/default/files/cap-workshop-2016-filtered-alert-hub_1.pdf

**Comment by frommberger** [comment]
I don't know if it applies, but be careful if the alert hub is meant to send email. AWS servers do have a bad reputation in the email universe, so they should better not be used for sending out important email.

**Comment by waidyanatha** [comment]
Current instance is setup here: http://52.220.44.232/eden/default/index
It will we revamped to serve with the data needs for: 

- the global cap feeds directory: https://sahanafoundation.org/global-cap-feed-directory/
- to serve as the filtered alert hub for clients to receive query specific feeds

contain a new style as drafted in the design: https://sites.google.com/sahanafoundation.org/sambro
