### ISSUE TITLE
Recruit Designer for CAP COP

### ISSUE THREAD

**Issue by devinbalkind** [sahana/SAMBRO#56]
I think we could potentially recruit a designer to improve how our CAP COP (http://sambro.geoinfo.ait.ac.th/eden/default/index/alert_hub_cop) is displayed. Do we have user stories, specifications, drawings, for how we'd like this to look? Can we create the materials a designer would need to get to work on this task?

**Comment by waidyanatha** [comment]
decided it was not an issue and a project strategy.
