### ISSUE TITLE
Import from URL

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#58]
I created a user account nuwan@sahanafoundation.org in http://sambro.geoinfo.ait.ac.th ; as an Authenticated User (i.e. not admin, editor, approver, or other). Now I want to use that account, in AIT demo server, to add a CAP feed in http://202.1.196.251 (Maldives server). Ger an "Insufficient Privileges " error? I am looged in as nuwan@sahanafoundation.org with Alert Editor and Alert Approver privileges in the Maldives server.

Another issue - only the Admin should be able to Import CAP feeds? the menu should not be visible to editors and approvers.

![error_url_form](https://cloud.githubusercontent.com/assets/543943/19292586/bd78895a-904f-11e6-8614-ee464f1b7ae5.png)

**Comment by biplovbhandari** [comment]
NB: This menu is for downloading individual alert like cap/alert/x.cap not cap/alert.rss which has separate menu. Also I think it makes more sense to provide this menu to alert editor and alert approver.

**Comment by waidyanatha** [comment]
If this done set label to Completed and indicate wiki URL

**Comment by biplovbhandari** [comment]
Linked from http://eden.sahanafoundation.org/wiki/UserGuidelines/SAMBRO#PublishersAlertIssuers (6) to http://eden.sahanafoundation.org/wiki/UserGuidelines/SAMBRO/Publish#ImportParticularAlertfromtheURLforRelay

**Comment by waidyanatha** [comment]
Let's try to keep the sub section headings short e.g. Import CAP with URL; something like that.
