### ISSUE TITLE
hide unnecessary/unused atributes

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#6]
@biplovbhandari Edit Subscription (/eden/pr/subscription/68) - shows an attribute called Filter but has no values in it. If there are meaningless attributes in any of the forms they should be hidden or removed. This is a tedious task of going though all the forms to ensure are no dangling attributes.

**Comment by biplovbhandari** [comment]
@waidyanatha there is nothing as /eden/pr/subscription/ID but /eden/pr/subscription. Might attach pic to clear

**Comment by biplovbhandari** [comment]
@waidyanatha You are looking wrong url. should be <i>/eden/default/index/subscriptions?subscription_id=XX</i> (<b>for self-subscription</b>) or <i>eden/default/index/subscriptions?option=manage_recipient&subscription_id=XX</i> (<b>for admin-based subscription</b>).

**Comment by waidyanatha** [comment]
Understand the problem that is 50% of the solution. Your comment is totally off beat and has nothing to do with what the reported issue is about. If you don't understand ask.

DO NOT CLOSE ISSUES UNTIL I HAVE VERIFIED!
