### ISSUE TITLE
default EMAIL subject

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#60]
The email subject for the deployments should not mention SAMBRO. Instead default to one that relates to their own domain. These are actual alerts that are received by people and should be meaningful. SAMBRO is internal.

**Comment by biplovbhandari** [comment]
I changed this for DMH/NDMC/PAGASA Alert Notification

**Comment by waidyanatha** [comment]
Closing this and moving it to the duplicate issue: https://github.com/sahana/SAMBRO/issues/61
