### ISSUE TITLE
https upgrade of servers

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#65]
We need to upgrade the Myanmar, Maldives, and Philippines servers to https before they can register their alert in WMO Register of Alerting Authorities. 

Philippines - may already have purchased a SSL certificate and would be simple to use that.

Myanmar, Maldives we may have to follow the free but limited option until they decided to purchase their own SSL certificate.

This website gives a basic cert (which is fine for now at least):  https://gethttpsforfree.com/
It is Trusted: https://letsencrypt.org/docs/faq/

The painful part at first is the 90 day renewal...so really that needs automating which is new to me, but I guess isn't that hard.

**Comment by waidyanatha** [comment]
https://letsencrypt.org/getting-started/

**Comment by frommberger** [comment]
Letsencrypt works like charm, automated renewal is not a pain at all, it's part of the service. It's all set up in less than an hour. Letsencrypt is coming with any recent Linux distribution. Go for it.

**Comment by flavour** [comment]
Looks awesome...I will investigate integrating this into standard Sahana installs (although that may not help the existing installs too much)

**Comment by waidyanatha** [comment]
adding SSL for HTTPS has been integrated with the EDEN installs; follow thread for more: https://groups.google.com/forum/#!msg/sahana-eden/kh78Xlj_rso/BZrdSQYYCwAJ
