### ISSUE TITLE
OID for Message Identifier

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#72]
The OID requires that it only contain integers and are separated by periods.
Example: 203.81.87.42-2.49.0.1.104.0.1-20170227-1184-Update
In this example, we need to remove the prefix and the suffix with "Update" or any other.
Typically, the identifier should be as this example - "urn:oid:2.49.0.1.462.1.2016.12.31.197.2"

We also need to set a Sahana policy to disallow creating a tree for each branch. If a division within a department wants a separate OID then the 7th integer should should be used to distinguish.

Another error is the 6th digits should be a 1 for the alert. The organization is identified with a 0 but then the 0 should be changed to 1 when it is used in an alert message.

**Comment by biplovbhandari** [comment]
https://github.com/sahana/eden/pull/1360

**Comment by waidyanatha** [comment]
Let me close these once I have verified because it doesn't seem these fixes are always complete ;-)
Moreover, we need to add the link to the wiki that discusses this aspect.
