### ISSUE TITLE
Unable to get SAMBRO runnin

### ISSUE THREAD

**Issue by Avasz** [sahana/SAMBRO#78]
Hello,

I am trying to get SAMBRO running. I have installed eden and it is working properly. But when I change the template to SAMBRO, i don't think it is working as intended. Things I did are:  

1. Changed template from 'default' to 'SAMBRO' in 000_config.py, and compiled.
 It gives this error
![screenshot from 2017-05-16 10-58-09](https://cloud.githubusercontent.com/assets/2859879/26090740/922cff84-3a26-11e7-94ef-3944c84e5ae4.png)

2. Copied config.py from SABRO folder as 000_config.py. It works, gives a stripped down interface of what default template shows, shown in screenshot below:
![screenshot from 2017-05-16 10-55-26](https://cloud.githubusercontent.com/assets/2859879/26090676/384d9c3a-3a26-11e7-8591-287e33a54292.png)

I am running it in Docker container with self built image because one in dockerhub is quite old and outdated too.

Any kind of help would be appreciated!
Thanks

**Comment by waidyanatha** [comment]
this is not the SAMBRO homepage (the one you have shown). Click on the error link to copy paste the error. The last line in the cascading error text will indicate the issue.

My sense is that after changing the template to SAMBRO you probably didn't run the "clean" command to import the staging data; but before we get to that let's see what your bug is, first.

**Comment by Avasz** [comment]
Yes, I did not run the clean command. How do I run it? because there is no such command by default.
I checked the Useful Aliases sections in the wiki too, and it is not alias.

The error message from Error Ticket shows this:
```python
Traceback (most recent call last):
  File "/home/web2py/gluon/restricted.py", line 224, in restricted
    exec ccode in environment
  File "file stream", line 425, in <module>
  File "/home/web2py/gluon/globals.py", line 405, in write
    self.body.write(xmlescape(data))
  File "/home/web2py/gluon/html.py", line 130, in xmlescape
    return data.xml()
  File "applications/eden/modules/s3/s3gis.py", line 7090, in xml
    self._setup()
  File "applications/eden/modules/s3/s3gis.py", line 6905, in _setup
    options["feature_resources"] = addFeatureResources(feature_resources)
  File "applications/eden/modules/s3/s3gis.py", line 7511, in addFeatureResources
    url = layer["url"]
KeyError: 'url'
```

I would like to write down the steps I did one by one.
1. Built image from dockerfile in the repo, replacing `ubuntu:14.04` to `ubuntu:latest`  
2. Ran `eden` in port 4000 of my server. hence `http://servername:4000/eden` works for eden.  
3. Copied `config.py` from `templates/SAMBRO/ ` as `000_config.py` inside the folder models.  
4. Compiled using the `compile` alias. 
5. Did not run `clean` as don't know how to do it.

Haven't done any prepopulation at all.

Thanks.

**Comment by flavour** [comment]
Clean is created by the deployment scripts...varies depending on the DB/Webserver as to contents, but example for Cherokee/PostGIS is here:
https://github.com/sahana/eden_deploy/blob/master/install-eden-cherokee-postgis.sh#L699

**Comment by flavour** [comment]
> Copied config.py from templates/SAMBRO/ as 000_config.py inside the folder models.

No, not the correct way to run a template, correct way is to set settings.base.template = "SAMBRO" in your 000_config.py:
http://eden.sahanafoundation.org/wiki/DeveloperGuidelines/Templates

**Comment by flavour** [comment]
PS Never used Docker, so cannot comment on those parts at all

**Comment by flavour** [comment]
> The error message from Error Ticket shows this

Yes, Nuwan correctly guessed that this is due to prepop not running, which is best done via 'clean'

**Comment by Avasz** [comment]
I did try changing `settings.base.template = "SAMBRO"` and `compile` too.

Also, I just found another ticket with this error message:  
`OperationalError: database is locked`  
I guess it means something is wrongly configured.

I wanted to initially try it in docker before running natively.

Thanks.

**Comment by Avasz** [comment]
I just checked the `clean` part of the script and now I think I need to install postgres and stuffs too, which I haven't done (according to dockerfile). Please suggest.

Thanks

**Comment by flavour** [comment]
> I did try changing settings.base.template = "SAMBRO" and compile too.

But didn't run prepopulate again, hence the problems (again, best done via 'clean' but more info here):
http://eden.sahanafoundation.org/wiki/DeveloperGuidelines/PrePopulate

> I just found another ticket with this error message:
> OperationalError: database is locked

You are running with the default SQLite DB which isn't really a multi-user DB...it does work fine for certain usecases, such as single-user laptops, but can give you this issue, especially if you are fiddling around with scripts which are modifying the DB

**Comment by flavour** [comment]
> now I think I need to install postgres and stuffs too, which I haven't done (according to dockerfile).     > Please suggest.

Depends on your usecase.Single user laptop is fine with the default SQLite.
Multi-user server shiould use a proper DB such as PostGIS or MySQL...which of those you use would again depend on your usecase (Spatial Queries?) & skillset

**Comment by biplovbhandari** [comment]
Hi @Avasz ! You have any particular requirement in SAMBRO? Feel free to shoot me an email at bionicbiplov45@gmail.com

**Comment by Avasz** [comment]
Thanks, but no particular requirements right now, just testing around.

I finally got SAMBRO working, but another problem. I am not able to register an account at all. THe first account I registered required admin approval, which I don't have.
BTW, I directly ran SAMBRO without running the 'default' template. Would that cause a problem?

Please suggest.

**Comment by biplovbhandari** [comment]
On Wed, May 17, 2017 at 3:37 PM, Avash Mulmi <notifications@github.com>
wrote:

> Thanks, but no particular requirements right now, just testing around.
>
> I finally got SAMBRO working, but another problem. I am not able to
> register an account at all. THe first account I registered required admin
> approval, which I don't have.
>

You can change the email settings in models/000_config.py and find
settings.mail.approver

When you prepopulate, admin@example.com (with pwd testing) gets the admin
role. You can try with that. You can create new account once you logged in.

> BTW, I directly ran SAMBRO without running the 'default' template. Would
> that cause a problem?
>

No it won't. If you want to play around with SAMBRO, then this is how you
should go. Or if you want to play around with different modules within
Sahana, you can start with default template.
ᐧ

**Comment by Avasz** [comment]
Thanks! I got it working with admin@example.com and testing. Going through it with my team.
This looks really nice, we are exploring more on this to know all of its workings. 

Thanks again!

**Comment by waidyanatha** [comment]
Avasz - glad you got it to work! If you have any further queries, recommend posting to the email list: sahana-eden@googlegroups.com.
