### ISSUE TITLE
Alert Editor cannot create Templates

### ISSUE THREAD

**Issue by waidyanatha** [sahana/SAMBRO#9]
See the roles: http://eden.sahanafoundation.org/wiki/UserGuidelines/SAMBRO#UserRolesandPermissions
Very important that users do not have permissions to functions they are not supposed to - Alert Editor has access to create Template, which should not be the case.

Also Alert Editor/Approver should not see the Alerts ---> Import Feeds URL. This is a function for the Implementer (Admin)

I noticed that several templates for floods that have been created, which should have been Alerts and not templates. Alert Editors should only see alerts and be able to create alerts. Alert Editors cannot create templates, only Admin can. Alert Editors are getting confused with templates and alerts. 

Go through all the forms to ensure menu items and functionality for each of the roles are properly defined and there are not lose ends.

**Comment by waidyanatha** [comment]
Even for Myanmar, the Editor should not be able to create templates. If at
all then that user should have Admin prole. Otherwise, they keep creating
templates for each different alert message. They have not grasped the
concept of a message template.

I don't recall Myanmar requesting that requirement because I would have
argued against it. Was this a conversation you had with them that I was not
aware of?

**Comment by biplovbhandari** [comment]
I think you were there when this conversation took place. Tun requested
this. I cannot remember if in email or IRC but it was requested by Tun.

**Comment by waidyanatha** [comment]
I explained to Tun today and he realizes now that Alert Editor does not need to create Templates and only the Admin does. Please roll back to our original permissions and roles schema; i.e. disable Alert Editor with permission to edit Templates and then close this task.

**Comment by waidyanatha** [comment]
Ensure that this is mentioned in the User Guide and then post URL here.

**Comment by waidyanatha** [comment]
Don't close them yet, I need to make sure the User Guideline content explains these issues. We should be able to direct users to the User Guide and FAQs when they ask these questions.

**Comment by biplovbhandari** [comment]
http://eden.sahanafoundation.org/wiki/FrequentlyAskedQuestionsSAMBRO

**Comment by flavour** [comment]
I would move that here: http://eden.sahanafoundation.org/wiki/UserGuidelines/SAMBRO/FAQ
